version: '3.3'

services:

  #Service #1 : definition of mysql database
  db: 
    image: mysql:latest
    container_name: mysql-db
    environment:
        - MYSQL_ROOT_PASSWORD=4PP32tNp9,#/Szr=
    volumes:
        - ./init.sql:/data/application/init.sql
    ports:
      - "3307:3306"
  api:
    build:
      context: ./cadegouline
    container_name: api      
    ports:
     - 3333:3333
    restart:
      always
    volumes:
        - /medias:/medias

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/property?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4PP32tNp9,#/Szr=

  front: 
    build:
      context: ./cadegouline-web
    container_name: frontapp
    ports:
      - 8080:8080
    restart:
      always
    depends_on:
      - api
  
  proxy:
    image: nginx
    volumes:
      - ./conf.d/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./conf.d/nginx/proxy_params:/etc/nginx/proxy_params

    ports: 
      - 80:80

